apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmchart.fullname" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.orderbook.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helmchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.orderbook.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helmchart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.orderbook.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helmchart.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.orderbook.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.orderbook.securityContext | nindent 12 }}
          image: "{{ .Values.orderbook.image.repository }}:{{ .Values.orderbook.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.orderbook.image.pullPolicy }}
          ports:
            - containerPort: 3001
              protocol: TCP
          resources:
            {{- toYaml .Values.orderbook.resources | nindent 12 }}          
      {{- with .Values.orderbook.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.orderbook.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.orderbook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
