apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
spec:
  type: {{ .Values.zookeeper.service.type }}
  clusterIP: None
  ports:
    - name: tcp-client
      port: {{ .Values.zookeeper.containerPorts.client }}
      targetPort: {{ .Values.zookeeper.containerPorts.client }}
    - name: tcp-follower
      port: {{ .Values.zookeeper.containerPorts.follower }}
      targetPort: {{ .Values.zookeeper.containerPorts.follower }}
    - name: tcp-election
      port: {{ .Values.zookeeper.containerPorts.election }}
      targetPort: {{ .Values.zookeeper.containerPorts.election }}
    # - name: tcp-client-tls
    #   port: {{ .Values.zookeeper.containerPorts.tls }}
    #   targetPort: {{ .Values.zookeeper.containerPorts.tls }}
  selector: {{- include "helmchart.selectorLabels" . | nindent 4 }}
    
