{{- if .Values.orderbook.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helmchart.serviceAccountName" . }}
  labels:
    {{- include "helmchart.labels" . | nindent 4 }}
  {{- with .Values.orderbook.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
