apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  type: ClusterIP
  ports:
    - port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.targetPort }}
      protocol: TCP
      name: kafka 
  selector:
    {{- include "helmchart.selectorLabels" . | nindent 4 }}
