apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
spec:
  type: {{ .Values.kafka.service.type }}
  clusterIP: None
  ports:
    - port: {{ .Values.kafka.service.port }}
      targetPort: {{ .Values.kafka.service.targetPort }}
      name: kafka-client
    - port: {{ .Values.kafka.containerPorts.internal }}
      targetPort: {{ .Values.kafka.containerPorts.internal }}
      name: kafka-internal 
  selector:
    {{- include "helmchart.selectorLabels" . | nindent 4 }}
